package SDA;

public class liczbaZnakowWTekscie {
    public static void main(String[] args) {
        String tekst = "\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent efficitur pulvinar arcu nec venenatis. Praesent euismod elementum nisi, id pharetra ipsum mattis vehicula. Praesent pellentesque nibh malesuada laoreet hendrerit. Proin blandit, tortor id volutpat pellentesque, odio mi aliquet lorem, efficitur aliquam neque urna vel dolor. Donec egestas ex ut ligula cursus, ac tincidunt tellus convallis. Aliquam pharetra urna non ligula sollicitudin interdum. Sed vehicula dui enim, id condimentum nulla finibus cursus. Nam malesuada nibh quis risus auctor, non vestibulum massa feugiat. Sed tincidunt convallis quam, id fermentum arcu scelerisque non. Nullam tincidunt et ante sit amet congue. Phasellus molestie ullamcorper elit, a vulputate mi aliquam id. Nam lobortis ex non aliquam sodales. Maecenas vitae dictum diam, ac placerat nulla. Nam ornare at metus sit amet aliquet. Quisque tristique mollis augue, ut ornare ipsum. Suspendisse auctor massa eget neque feugiat, viverra consectetur dui convallis.\\n\" +\n" +
                "                \"\\n\" +\n" +
                "                \"Pellentesque convallis cursus ultrices. Donec pellentesque a velit eget varius. Nulla ultrices volutpat augue, vel auctor risus bibendum at. Praesent molestie massa et arcu tincidunt laoreet. Nunc facilisis, orci eleifend commodo pulvinar, dui est pharetra nibh, blandit consequat nisl libero a turpis. Aenean eu urna in neque tristique vehicula non in odio. Etiam vitae neque sit amet nunc mollis facilisis ac id enim. Etiam metus odio, pharetra vitae est quis, ornare ultricies sem.\\n\" +\n" +
                "                \"\\n\" +\n" +
                "                \"Cras ullamcorper mi arcu, semper laoreet est tristique ut. Nullam diam turpis, placerat id velit ac, ultricies laoreet ligula. Praesent nec arcu dui. Donec scelerisque, felis et congue sollicitudin, risus lectus viverra metus, elementum efficitur mi nibh non turpis. Nunc viverra, augue in interdum tempus, leo metus pharetra diam, id euismod ante ligula non tortor. Sed tincidunt lacus ut dui venenatis, in pellentesque arcu tincidunt. Proin a dui est. Ut hendrerit tristique eros. Curabitur non lacus eu magna volutpat tempor. Phasellus lobortis malesuada urna ut dictum. Donec at velit quis arcu vulputate faucibus id eget nulla.\\n\" +\n" +
                "                \"\\n\" +\n" +
                "                \"Quisque maximus fermentum dui, vel ullamcorper est imperdiet sed. Nulla purus massa, volutpat id nisi vitae, facilisis vulputate nisl. Nullam ut magna ac eros venenatis pretium et sit amet ex. Donec euismod tincidunt odio, vel varius elit congue at. Proin et purus non turpis sagittis ullamcorper. Suspendisse tristique metus nec nisl pulvinar, congue auctor elit ultricies. Praesent at nisi nisl. Praesent finibus sagittis velit, commodo consequat sem. Nunc auctor mi ac elit consectetur, et aliquam ante imperdiet. Vestibulum eget tempus eros. Nullam viverra feugiat eros id vulputate. Sed mollis fringilla bibendum.\\n\" +\n" +
                "                \"\\n\" +\n" +
                "                \"Suspendisse consequat, risus id pellentesque auctor, eros enim dignissim lectus, non lobortis nisi orci et metus. Cras consectetur neque sed fringilla efficitur. Nullam porta tortor a libero eleifend, nec pretium felis aliquam. Nunc ac mi convallis, varius nunc quis, dignissim neque. Aenean faucibus tellus sit amet sapien blandit, a dapibus ligula commodo. Praesent cursus in libero eu auctor. Duis ultrices posuere lectus ac aliquet. Nam sagittis tellus nec mauris tempus tincidunt non vel nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dui nunc, fringilla in urna vitae, molestie accumsan dolor. Mauris tempus massa est, eget tincidunt dolor mollis ut. Integer euismod, massa ut pharetra convallis, eros elit sodales ligula, non aliquam purus nulla eget justo.";
        System.out.println(tekst.length());
        System.out.println(tekst.substring(10,30).toLowerCase());
        System.out.println(tekst.substring(10,30).toUpperCase());
        System.out.println(tekst.isEmpty());

    }
}
